version: "2"
services:
  order-wfm:
    image: owfm
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    command: "nodemon server.js"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
  test:
    image: "owfm"
    volumes:
      - ".:/app"
    command: "npm test"
